#!/usr/bin/env python3
"""strip_code_tex.py — strip NovaScript code blocks and output as LaTeX.

Generates a LaTeX document suitable for typesetting a visual novel script.
Dialogue uses the `stageplay` or custom dialogue macros.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path
from typing import Optional

SCRIPT_PATH = Path(__file__).resolve()
PROJECT_ROOT = SCRIPT_PATH.parents[2]


class CliError(Exception):
    """An invocation or infrastructure error that returns exit code 2."""


DIALOGUE_PATTERN = re.compile(r'^(.+?)：：\u201c(.+?)\u201d\s*$')
CODE_BLOCK_START = re.compile(r'^@?<\|')
CODE_BLOCK_END = re.compile(r'\|>\s*$')

LATEX_PREAMBLE = r"""\documentclass[a4paper,12pt]{article}
\usepackage[UTF8]{ctex}
\usepackage{geometry}
\geometry{margin=2.5cm}
\usepackage{setspace}
\onehalfspacing

% Dialogue macros
\newenvironment{script}{%
  \setlength{\parindent}{0pt}%
  \setlength{\parskip}{6pt}%
}{}

\newcommand{\speaker}[1]{%
  \textbf{#1}：%
}

\newcommand{\narration}[1]{%
  {\itshape\small #1}%
}

\newcommand{\stagedir}[1]{%
  {\footnotesize (#1)}%
}

\title{%TITLE%}
\author{Generated by Uni-Story strip\_code\_tex}
\date{\today}

\begin{document}
\maketitle
\begin{script}
"""

LATEX_POSTAMBLE = r"""\end{script}
\end{document}
"""


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Strip NovaScript code blocks and output as LaTeX.",
    )
    parser.add_argument(
        "--input", "-i", metavar="PATH", required=True,
        help="input NovaScript scenario file",
    )
    parser.add_argument(
        "--output", "-o", metavar="PATH", default="-",
        help="write LaTeX output to PATH, or '-' for stdout (default: -)",
    )
    parser.add_argument(
        "--title", metavar="TITLE",
        help="document title (default: input filename)",
    )
    parser.add_argument(
        "--project", metavar="PATH",
        help="project root (defaults to repository root)",
    )
    return parser


def resolve_project_root(explicit: str | None) -> Path:
    if explicit:
        p = Path(explicit).resolve()
        if not p.is_dir():
            raise CliError(f"project root not found: {p}")
        return p
    return PROJECT_ROOT


def _escape_tex(text: str) -> str:
    """Escape special LaTeX characters."""
    replacements = [
        ("\\", r"\textbackslash{}"),
        ("&", r"\&"),
        ("%", r"\%"),
        ("$", r"\$"),
        ("#", r"\#"),
        ("_", r"\_"),
        ("{", r"\{"),
        ("}", r"\}"),
        ("~", r"\textasciitilde{}"),
        ("^", r"\textasciicircum{}"),
    ]
    for old, new in replacements:
        text = text.replace(old, new)
    return text


def strip_to_tex(filepath: Path, title: str | None) -> str:
    try:
        raw = filepath.read_text(encoding="utf-8")
    except Exception as exc:
        raise CliError(f"cannot read {filepath}: {exc}") from exc

    doc_title = _escape_tex(title or filepath.stem)
    preamble = LATEX_PREAMBLE.replace("%TITLE%", doc_title)

    lines = raw.splitlines()
    body: list[str] = []
    in_code = False
    blank_count = 0

    for line in lines:
        stripped = line.strip()

        if CODE_BLOCK_START.match(stripped):
            in_code = True
            continue
        if in_code:
            if CODE_BLOCK_END.match(stripped):
                in_code = False
            continue

        if not stripped:
            blank_count += 1
            if blank_count <= 1:
                body.append("")
            continue
        blank_count = 0

        m = DIALOGUE_PATTERN.match(stripped)
        if m:
            speaker = _escape_tex(m.group(1).strip())
            text = _escape_tex(m.group(2).strip())
            body.append(f"\\speaker{{{speaker}}}{{{text}}}")
        else:
            body.append(f"\\narration{{{_escape_tex(stripped)}}}")

    return preamble + "\n".join(body) + "\n" + LATEX_POSTAMBLE


def main() -> None:
    args = _parser().parse_args()
    try:
        project_root = resolve_project_root(args.project)
    except CliError as e:
        print(str(e), file=sys.stderr)
        sys.exit(2)

    input_path = Path(args.input)
    if not input_path.is_absolute():
        cwd_fp = Path.cwd() / input_path
        proj_fp = project_root / input_path
        input_path = cwd_fp if cwd_fp.exists() else proj_fp
    if not input_path.is_file():
        print(f"strip_code_tex: error: input file not found: {input_path}", file=sys.stderr)
        sys.exit(2)

    try:
        result = strip_to_tex(input_path, args.title)
    except CliError as e:
        print(f"strip_code_tex: error: {e}", file=sys.stderr)
        sys.exit(2)

    if args.output == "-":
        sys.stdout.write(result)
    else:
        out_path = Path(args.output)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(result, encoding="utf-8")


if __name__ == "__main__":
    main()
